name: Android Build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      buildtype:
        type: choice
        description: Build Type
        options:
          - Release
          - Debug
        default: Release

jobs:
  android:
    name: Android (${{ matrix.abi }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - abi: armeabi-v7a
          - abi: arm64-v8a

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK r25c
        run: |
          echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "ndk;25.2.9519653"
          echo "ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Install Ninja & CMake
        run: sudo apt-get update && sudo apt-get install -y ninja-build cmake

      - name: Configure (${{ matrix.abi }})
        run: |
          cmake -G Ninja -S . -B build-${{ matrix.abi }} \
            -DCMAKE_TOOLCHAIN_FILE="cmake/android-${{ matrix.abi }}.cmake" \
            -DANDROID_NDK="${ANDROID_NDK}" \
            -DCMAKE_BUILD_TYPE=${{ github.event.inputs.buildtype || 'Release' }} \
            -DANDROID_APK=ON \
            -DCMAKE_INSTALL_PREFIX="${PWD}/dist/${{ matrix.abi }}"

      - name: Build (${{ matrix.abi }})
        run: cmake --build build-${{ matrix.abi }} --parallel

      - name: Install (${{ matrix.abi }})
        run: cmake --install build-${{ matrix.abi }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '_')" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Upload artifact (${{ matrix.abi }})
        uses: actions/upload-artifact@v4
        with:
          name: wantedhl-android-${{ matrix.abi }}-${{ steps.extract_branch.outputs.branch }}
          path: dist/${{ matrix.abi }}
